global:
  scrape_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'webapp'
    
    metrics_path: /metrics 
    static_configs:
      - targets: ['webapp:8080'] 

